name = "lanka-weather"
pages_build_output_dir = "public"
compatibility_date = "2026-06-11"
compatibility_flags = ["nodejs_compat"]

[vars]
# මෙතන API Key එක දාන්න එපා, Cloudflare Dashboard එකේම දාන්න
